config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :posts, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: :create
  end 
  resources :users, only: [:index, :show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true
  validates :user, presence: true
  validates :text, presence: true
 
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
validates :image,      presence: true
has_many :comments, dependent: :destroy
belongs_to :user
has_one_attached :image

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: '英字と数字の両方を含めて設定してください', on: :create
  
  validates :name, presence: true

  has_many :posts
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]  
  end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
       redirect_to post_path(@comment.post)
    else
      @post = @comment.post
      @comments = @post.comments
      render "posts/show"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id]) 
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :move_to_index, only: [:edit, :update, :destroy]

  def index
    @posts = Post.includes(:user).order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments
  end 

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path
    else
      render :edit 
    end  
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end 

  private

  def post_params
    params.require(:post).permit(:title, :catch_copy, :concept, :image).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def move_to_index
    redirect_to root_path unless current_user == @post.user
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja" >
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ShareGreen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/968836844b.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
            <%# ログインしているときは以下を表示するようにしましょう %>
            <% if user_signed_in? %>
             <%= link_to "投稿一覧", root_path, class: :nav__btn %>
             <%= link_to "ユーザー一覧", users_path, class: :nav__btn %>
             <%= link_to "新規投稿", new_post_path, class: :nav__btn %>
          </div>
            <div class="nav__right"> 
              <%= link_to "マイページ", user_path(current_user.id), class: :nav__btn %> 
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__btn %>
            </div> 
          <% else %>
            <%# ログインしていないときは以下を表示するようにしましょう %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © 2020-2021 Daddy Plants All Rights Reserved.</p>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered ">
      <div class="column is-6 ">
        <%= form_with model: @post, local: true do |f| %>
          <div class="field">
            <%= f.label :title, "植物名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :catch_copy, "生育環境", class: "label" %>
            <%= f.text_area :catch_copy, class: "textarea" %>
          </div>
        
          <div class="field">
            <%= f.label :concept, "キャプション", class: "label" %>
            <%= f.text_area :concept, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.file_field :image %>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/posts/_post.html.erb
<div class="card">
  <%= link_to image_tag(post.image, class: :card__img ), post_path(post.id), method: :get %>
  <div class="card__body">
    <%= link_to post.title, post_path(post.id), class: :card__title%>
    <p class="card__summary">
      <%= post.catch_copy %>
    </p>
    <%= link_to "by #{post.user.name}", user_path(post.user_id), class: :card__user %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading"></h2>
      <%# 部分テンプレートでフォームを表示する %>
      <%= render "form", local: { post: @post } %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<main class="main">
  <div class="inner">
    <div class="card__wrapper">
      <%= render partial: "post", collection: @posts %>
    </div>
      <div class="main-image">
    </div>
  </div>
</main>

app/views/posts/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
       <h2 class="page-heading"></h2>
        <%# 部分テンプレートでフォームを表示する %>
       <%= render partial: "form", local: { post: @post } %> 
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @post.title %>
      </p>
      <%= link_to "by #{@post.user.name}", user_path(@post.user.id), class: :prototype__user %>
      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
      <% if user_signed_in? && current_user.id == @post.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集", edit_post_path, class: :prototype__btn %>
          <%= link_to "削除", post_path(@post.id), method: :delete, class: :prototype__btn %>
        </div>
      <% end %>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="prototype__image">
        <%= image_tag @post.image %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title"></p>
          <p class="detail__message">
            <%= @post.catch_copy %>
          </p>
        </div>
      <div class="prototype__detail">
          <p class="detail__title"></p>
          <p class="detail__message">
            <%= @post.concept %>
         </p>
      </div>
   </div>  
  <div class="prototype__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
      
        <%# // ログインしているユーザーには上記を表示する %>
          <ul class="comments_lists">
            <%# 投稿に紐づくコメントを一覧する処理を記述する %>
            <% @comments.each do |comment| %>
              <% if @comments %>
                  <li class="comments_list">
                    <%= comment.text %>
                    <%= link_to comment.user.name, user_path(comment.user_id), class: :comment_user %>
                  </li>
              <% end %>
            <% end %>
           <% if user_signed_in? %>
            <%= form_with model: [@post, @comment], local: true do |f|%>
             <div class="field">
              <%= f.label :text, "コメント" %><br />
              <%= f.text_field :text %>
             </div>
             <div class="actions">
               <%= f.submit "送信する", class: :form__btn  %>
             </div>
            <% end %> 
          <% end %>
        </ul>
      </div>
  </div>
</main>

app/views/users/edit.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_with model: @user, local: true do |f| %>
          <div class="field">
            <%= f.label :name, "ユーザー名", class: "label" %>
            <%= f.text_field :name, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :email, "メールアドレス", class: "label" %>
            <%= f.email_field :email, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :profile_image, "プロフィール画像", class: "label" %>
            <%= f.attachment_field :profile_image %>
          </div>

          <%= f.submit "Update", class: "button is-success" %>
        <% end %>

      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card-a">
            <div class="card-content-a">
              <div class="card-image-a">
                <figure class="image-a">
                  <%= link_to user_path(user.id) do%>
                     <%= attachment_image_tag user, :profile_image, fallback: "noimage.png", class: "profile_image"  %>
                    <%=link_to user.name, user_path(user.id)%>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content-a">
              <div class="media">
                <div class="media-content">
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="section">
  <div class="container ">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image-a is-128x128"  style="margin-left: auto; margin-right: auto;">
              <%# <%= attachment_image_tag @user, :profile_image, fallback: "noimage.png", class: "profile_image is-rounded" %>  
              <%# <%= image_tag attachment_url(@user, :profile_image, fallback: "noimage.png", class: "profile_image is-rounded") %>
              <%= attachment_image_tag @user, :profile_image, fallback: "noimage.png", class: "profile_image" %> 
            </figure>
          </div>
          <div class="column is-7">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.name %></strong>
                    <% if current_user.id == @user.id %>
                    <%= link_to "編集", edit_user_path(@user.id), class: "button" %>
                    <% end %>
                </td>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile %>
                </td>  
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<section class="section">
  <div class="container ">
    <div class="columns is-multiline">
      <% @user.posts.each do |post| %>
        <%# <div class="column"> %>
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
               <%= link_to post_path(post) do %>
                  <%= image_tag post.image %>
                <% end %>
              </figure>
            </div>
              <div class="content">
                <time><%= post.updated_at.strftime("%Y-%m-%d %H:%M") %></time>
              </div>
          </div>
        <%# </div> %>
      <% end %>
    </div>
  </div>
</section>